#!/bin/sh
set -e
if test ! -f Makefile.in ; then
  ./autogen
fi
if test ! -f Makefile ; then
  ./configure
fi
make dist-gzip
cur=$(pwd)
mkdir /tmp/t$$
cd /tmp/t$$
tar xvfz $cur/libcompl*.tar.gz
cd */
./configure
make
test -x tools/ncd
./tools/ncd
exit 0
